server:
  port: 10002

spring:
  application:
    name: market-service
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: market-service
      value-deserializer: com.github.efreeti.trading.events.config.Jdk8JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.github.efreeti.trading.events.domain
    producer:
      value-serializer: com.github.efreeti.trading.events.config.Jdk8JsonSerializer
      batch-size: 1
