version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - network1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - network1

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONNECTIONS_FROM_HOST://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - 19092:19092
    networks:
      - network1

  account-service:
    container_name: account-service
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    networks:
      - network1
    ports:
      - "10000:10000"
    depends_on:
      - kafka
      - mongo

  order-service:
    container_name: order-sesrvice
    build:
      context: ./order-service
      dockerfile: ./Dockerfile
    networks:
      - network1
    ports:
      - "10001:10001"
    depends_on:
      - kafka
      - mongo

  market-service:
    container_name: market-service
    build:
      context: ./market-service
      dockerfile: ./Dockerfile
    networks:
      - network1
    ports:
      - "10002:10002"
    depends_on:
      - kafka

networks:
  network1:
