server:
  port: 10001

spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: order-service
      value-deserializer: com.github.efreeti.trading.events.config.Jdk8JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.github.efreeti.trading.events.domain
    producer:
      value-serializer: com.github.efreeti.trading.events.config.Jdk8JsonSerializer
      batch-size: 1
